# Use the official Golang image as the base image
FROM golang:1.19

# Set the working directory inside the container
WORKDIR /app

# Copy go.mod and go.sum files to the working directory
COPY go.mod go.sum ./

# Download all dependencies. Dependencies will be cached if the go.mod and go.sum files are not changed
RUN go mod download

# Copy the rest of the application code to the working directory
COPY . .

# Build the Go application
RUN go build -o apihexhandler main.go

# Expose the port the application runs on
EXPOSE 8081

# Set environment variables (if needed)
ENV PORT=8081

# Command to run the executable
CMD ["./apihexhandler"]
