# Imagen base de Go
FROM golang:1.19

# Crear y establecer el directorio de trabajo
WORKDIR /app

# Copiar archivos del proyecto
COPY . .

# Descargar dependencias y compilar
RUN go mod tidy && go build -o api_returner main.go

# Copiar el archivo .env si existe
COPY .env /app/.env

# Exponer el puerto de la API Returner
EXPOSE 8082

# Ejecutar la API
CMD ["./api_returner"]
