# Imagen base de Go
FROM golang:1.19

# Crear y establecer el directorio de trabajo
WORKDIR /app

# Copiar archivos del proyecto
COPY . .

# Descargar dependencias y compilar
RUN go mod tidy && go build -o consumer main.go

# Copiar el archivo .env si existe
COPY .env /app/.env

# Ejecutar el consumidor
CMD ["./consumer"]
